services:
  - type: web
    name: script-psych-architect
    runtime: static
    buildCommand: npm ci --production=false && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: SKIP_INSTALL_DEPS
        value: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html